version: "3"
services:
  application:
    image: crudimage
    ports:
      - 8090:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcontainer:3306/movies?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sail
    depends_on:
      - mysqldb
    networks:
      - networkmysql

  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: sail
      MYSQL_DATABASE: movies
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    networks:
      - networkmysql

networks:
  networkmysql:
    external: true
